### ISSUE TITLE
BUG Wear Leveling + FAT FS Init

### ISSUE THREAD

**Issue by timoxd7** [AerofoilsGmbH/esp-idf#4]
## Info
See esp-idf\components\fatfs\vfs\vfs_fat_spiflash.c:92

After WL is init, the fatfs gets init and on fail will make a partition erase. This circumvents the WL layer, making it broken on close.

## Solution
Deinit WL prior partition erase and init again afterwards.

**Comment by giga993** [comment]
Maybe do a PR or an Issue in official esp idf repo
